---
title: "Data Requirements"
---

### Data Preparation

It is required that the data are prepared as a long-format data, where each row is data for a unique case, namely, a specific task from a specific person in a specific testing occasion. In the context of ORF assessment, each row is data for a specific passage from a specific student in a specific testing occasion. A data file can be prepared in any file format that is readable into R.

For example, a CSV formatted data can be read into R by using the `read.csv()` function that is part of the base packages. Also, data files in some statistical software formats can be read in to R with functions in packages, such as the `haven` package. For example, `read_spss()` function can be used to read in an SPSS formatted data file into R.

Data should minimally contain the following 5 variables:

\(1\) individual ID, \
(2) task ID, \
(3) the maximum number of attempts in the task, \
(4) the number of successes in the task, and \
(5) the time took to complete the task.

Variable names and the order of the variables can be flexible in the data frame. When running functions in this package, variable names for required variables need to be specified, as shown in examples shown in the Tutorial section.

### Example Data sets in `bspam` R Package

The `bspam` R package comes with several example data sets in the ORF assessment context. In the context of an ORF assessment, a task is a passage given to the student to read aloud, and an attempt is student’s reading on a word in the passage, which is scored correct (i.e., success) or not. Accordingly, the number of successes in the task is the number of words correctly read in the passage.

For example, the data set `passage2` is a passage-level student data and consisted of reading accuracy and time data for 12 passages from 85 students. Although the 85 students were assigned to all 12 passages, the number of passages read by the 85 students varied from 2 to 12 passages. The number of students per passage were between 59 to 79. This is a small subset of the data collected by Nese and Kamata (2014-2018).

A list of all data sets in the `bspam` package is as follows.

| Data Object Name      | Brief Description                               |
|-----------------------|-------------------------------------------------|
| `passage2`            | Passage-level ORF example data                  |
| `sentence.level.data` | Sentence-level/testlet ORF example data         |
| `sentence.cens.low`   | Sentence-level example data with low censoring  |
| `sentence.cens.high`  | Sentence-level example data with high censoring |

The package also includes two calibration output objects. These objects can be directly used in the `scoring()` function bypassing the calibration step. They are potentially useful for those who wish to manually produce a calibration output object for scoring, such as in a simulation study.

| Output Object Name | Brief Description |
|-------------------------|-----------------------------------------------|
| `passage.calib.mcem` | Example MCEM calibration output object with `passage2` data |
| `passage.calib.bayes` | Example Bayesian calibration output object with `passage2` data |
