---
title: "What is bspam?"
---

## Overview

`bspam` is named after **S**peed-**A**ccuracy **P**sychomeric **M**odeling for **B**inomial count outcome data. It is an R package that contains functions to fit the speed-accuracy latent variable psychometric model for repeatedly measured count outcome data (Potgieter, Kamata & Kara, 2017; Kara, Kamata, Potgieter & Nese, 2020; Potgider, Kamata, Kara, & Qiao, 2025), which is an extension of van der Linden (2007). In the `bspam` model, the accuracy and speed are modeled by a binomial count and a log-normal latent variable models, respectively. It also estimates speed and accuracy latent factor scores as described in Potgieter, Qiao, Kamata, and Kara (2024) and Kara, Kamata, Potgieter, and Nese (2020). For example, the use of this modeling technique allows model-based calibration and scoring for oral reading fluency (ORF) assessment data, estimating model-based WCPM scores.

## Acknowledgement

The development of `bspam` R package and Shiny App was supported by the Institute of Education Sciences, U.S. Department of Education, through Grant R305D200038 to Southern Methodist University.

## Copyright Statement

Copyright (C) 2022-2026 The ORF Project Team

The bspam package is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.

The bspam package is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this package. If not, see <http://www.gnu.org/licenses/>.
